### ISSUE TITLE
proposal is onvoldoende

### ISSUE THREAD

**Issue by stgm** [jochemvandooren/Programmeerproject#1]
er staat niet eens een inleidende zin met wat je gaat maken! en draai de plaatjes even netjes. graag medestudenten om advies vragen (even spieken).

**Comment by jochemvandooren** [comment]
@stgm Ik heb het gefixed. Ook heb ik de schetsen meteen specifieker en mooier gemaakt. Hopelijk is het goed.

**Comment by stgm** [comment]
Ziet er duidelijk uit. Zo zie ik wel dat het net een beetje mager lijkt. Denk even na over een extra scherm/feature die je zou kunnen toevoegen!

**Comment by jochemvandooren** [comment]
@stgm Daar was ik al bang voor, daarom had ik bedacht dat ik bijvoorbeeld de route naar het object wat de gebruiker wil zoeken kan uitstippelen. Ik weet alleen niet of dit realistisch/te makkelijk is.

**Comment by stgm** [comment]
Nee, om dat goed te doen kun je beter uitwijken naar de hulp van bestaande planners :-)
Ik heb nog "beacons" die je zou kunnen tracken. Dan kun je automatisch bijhouden wanneer je wegloopt van het te tracken object.

**Comment by jochemvandooren** [comment]
@stgm Als het mogelijk is om die beacons te gebruiken en als de app hierdoor uitdagend genoeg wordt, zou ik die graag gebruiken!

**Comment by stgm** [comment]
Ja, dat is prima. Zie http://developer.estimote.com - ik kom straks nog even langs, dan krijg je er twee.
